In [30]:
import numpy as np
import math

In [31]:
# Q1)

In [32]:
print(x)

NameError: name 'x' is not defined

In [33]:
list = [1,2,3]
print(list[4])

IndexError: list index out of range

In [34]:
dictionary = {}
print(dictionary[20])

KeyError: 20

In [43]:
num = 9
print("num is " + num)

TypeError: can only concatenate str (not "int") to str

In [35]:
print(int('5.0'))

ValueError: invalid literal for int() with base 10: '5.0'

In [36]:
y = 1
z = 0
print(y/z)

ZeroDivisionError: division by zero

In [37]:
# Q2)
if 'Python' in 'Python is great!':
    print("Yes")
else:
    print("No")

Yes


In [38]:
# Q3)
str = 'Python is great!'
ans3 = str.split(" ")
print(ans3)

['Python', 'is', 'great!']


In [39]:
# Q4)
list = [2,3,2,3,1,2,5,3,2,3,3,2]
ans4 = []
count_list = {}
for i in list:
    if i in count_list:
        count_list[i] += 1
    else:
        count_list[i] = 1
for i in count_list:
    if (count_list[i] == 1):
        ans4.append(i)
print("Unique elements are: ", ans4)

Unique elements are:  [1, 5]


In [40]:
# Q5)
set_a = {3,2,1}
set_b = {2,3,2}
print("Union of set_a and set_b is ", set_a.union(set_b))
print("Intersection of set_a and set_b is ", set_a.intersection(set_b))
print("Difference of set_a to set_b is ", set_a.difference(set_b))

Union of set_a and set_b is  {1, 2, 3}
Intersection of set_a and set_b is  {2, 3}
Difference of set_a to set_b is  {1}


In [41]:
# Q6)
y = np.array([[3,5,3],[2,2,5],[3,8,9]])
y_t = y.transpose()
print("Transpose of the matrix is\n", y_t)
ans6_1 = y.dot(y_t)
print("yy^T :\n", ans6_1) 
ans6_2 = y_t.dot(y)
print("y^Ty : \n", ans6_2)
if np.array_equal(ans6_1, ans6_2) : 
    print("Both are equal")
else:
    print("Both are unequal")
z = y.reshape(9,1)
print("z : \n",z)
z_t = z.transpose()
print("z^T : \n",z_t)
ans6_3 = z.dot(z_t)
ans6_4 = z_t.dot(z)
print("zz^T :\n", ans6_3)
print("z^Tz :\n", ans6_4)
if np.array_equal(ans6_3, ans6_4) :
    print("Both are equal")
else: 
    print(f"Both are unequal.\nzz^T is a {len(ans6_3)} * {len(ans6_3[0])} matrix.\nz^Tz is a {len(ans6_4)} * {len(ans6_4[0])} matrix")

Transpose of the matrix is
 [[3 2 3]
 [5 2 8]
 [3 5 9]]
yy^T :
 [[ 43  31  76]
 [ 31  33  67]
 [ 76  67 154]]
y^Ty : 
 [[ 22  43  46]
 [ 43  93  97]
 [ 46  97 115]]
Both are unequal
z : 
 [[3]
 [5]
 [3]
 [2]
 [2]
 [5]
 [3]
 [8]
 [9]]
z^T : 
 [[3 5 3 2 2 5 3 8 9]]
zz^T :
 [[ 9 15  9  6  6 15  9 24 27]
 [15 25 15 10 10 25 15 40 45]
 [ 9 15  9  6  6 15  9 24 27]
 [ 6 10  6  4  4 10  6 16 18]
 [ 6 10  6  4  4 10  6 16 18]
 [15 25 15 10 10 25 15 40 45]
 [ 9 15  9  6  6 15  9 24 27]
 [24 40 24 16 16 40 24 64 72]
 [27 45 27 18 18 45 27 72 81]]
z^Tz :
 [[230]]
Both are unequal.
zz^T is a 9 * 9 matrix.
z^Tz is a 1 * 1 matrix


In [42]:
#Q7)
%whos
%reset -f
%whos

Variable     Type       Data/Info
---------------------------------
ans3         list       n=3
ans4         list       n=2
ans6_1       ndarray    3x3: 9 elems, type `int64`, 72 bytes
ans6_2       ndarray    3x3: 9 elems, type `int64`, 72 bytes
ans6_3       ndarray    9x9: 81 elems, type `int64`, 648 bytes
ans6_4       ndarray    1x1: 1 elems, type `int64`, 8 bytes
count_list   dict       n=4
dictionary   dict       n=0
i            int        5
list         list       n=12
math         module     <module 'math' (built-in)>
np           module     <module 'numpy' from '/ho<...>kages/numpy/__init__.py'>
set_a        set        {1, 2, 3}
set_b        set        {2, 3}
str          str        Python is great!
y            ndarray    3x3: 9 elems, type `int64`, 72 bytes
y_t          ndarray    3x3: 9 elems, type `int64`, 72 bytes
z            ndarray    9x1: 9 elems, type `int64`, 72 bytes
z_t          ndarray    1x9: 9 elems, type `int64`, 72 bytes
Interactive namespace is empty.
